title: "Jekyll Plugins • Community-built plugins to level up your Jekyll experience."
repository: https://github.com/jekyll/plugins
url: https://jekyll.github.io
baseurl: /plugins
lang: "en_US"

gems:
    - jekyll-sitemap
    - jemoji

collections:
  plugins:
    output: true

defaults:
  - scope:
      type: plugins
    values:
      permalink: /plugins/:title/ # DO NOT CHANGE THIS DEFAULT
      layout: plugin              # DO NOT CHANGE THIS DEFAULT
      type: rubygems              # DO NOT CHANGE THIS DEFAULT

exclude:
  - vendor
  - Gemfile*
  - Rakefile
  - README.md
  - CONTRIBUTING.md
  - History.markdown
  - spec
  - script
