title: "Jekyll Plugins • Community-built plugins to level up your Jekyll experience."
repository: https://github.com/jekyll/plugins
baseurl: /plugins

gems:
    - jekyll-sitemap

collections:
  plugins:
    output: true
    permalink: /:title/

exclude:
  - vendor
  - Gemfile*
  - Rakefile
  - README.md
  - spec
  - script
